---
name: parley
version: 17.08.1
summary: vocabulary trainer
description: |-
 Parley is a utility to help train vocabulary when learning a foreign language.
 It is intended as a replacement for flash cards.
confinement: strict
grade: stable
apps:
    parley:
        command: kf5-launch parley
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    parley:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libxml2-dev
        - libxslt-dev
        - imagemagick
        - kross-dev
        - libkeduvocdocument-dev
        source: https://download.kde.org/stable/applications/17.08.1/src/parley-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
